### ISSUE TITLE
Consider IspybApi tag interface

### ISSUE THREAD

**Issue by phathaway** [DiamondLightSource/gda-ispyb-api#1]
I note that grouping stored procedure access by interface has commenced with `IspybPlateApi` and `IspybPdfInterface`.

rather than eliminating the `IspybApi` interface class, consider using it as a _tag_ interface (no methods) that any new API group extends. For example:
`IspybPlateApi extends IspybApi`.

This may assist maintaining references to a collection of implementations when sophisticated clients need access to more than one.

**Comment by kevinpetersavage** [comment]
I don't see the benefit of this, e.g.:  

ISpybApi iSpybApi = new ArrayList<ISpybApi>().get(0);
// have to cast here before you can call it

Do you have a different use case?

**Comment by phathaway** [comment]
Conceptually a tag interface does convey some type information, showing that the instances do have a type relationship - they are both a-kind-of ispy api class. This is useful for any kind of utility class that uses more than one. eg  `List<IspybApi>` or `Map<key,IspybApi>`
In these simplistic cases a cast is still required, but not a blind cast as you are guaranteed that the collection contains ISpybApi objects rather than just Objects.
More generally, using the tag interface will let you add new sub-classes without changing the way you store them or pass them around.

An example of a more sophisticated use is using an extension point to provide a custom IspybApi that is still compatible with any or all utility classes designed to interact with an ISpybApi type.

I do not have a current use case - you have only just started adding new IspybApi-type classes. However, we already know that we expect more, and have to consider how we handle them, including extending the factory class for each one.

Other reasons to use tag interfaces generally:
[http://www.javapractices.com/topic/TopicAction.do?Id=240](url)

**Comment by phathaway** [comment]
Accidentally closed. Then re-opened.

**Comment by phathaway** [comment]
Use of generics accepted.
